# Generated by Django 2.0.6 on 2018-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(db_column='sfid', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, db_column='password__c', max_length=100, null=True)),
                ('password_token', models.UUIDField(blank=True, db_column='password_token__c', null=True)),
                ('is_active', models.BooleanField(db_column='is_active__c', default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date__c')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='update_date__c')),
            ],
            options={
                'db_table': '"salesforce"."contact"',
                'ordering': ['-updated_date'],
            },
        ),
    ]
