# Generated by Django 2.0.6 on 2018-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(db_column='sfid', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('content', models.TextField(blank=True, db_column='content__c', null=True)),
                ('is_active', models.BooleanField(db_column='is_active__c', default=False)),
                ('active_date', models.DateTimeField(db_column='active_date__c')),
            ],
            options={
                'db_table': '"salesforce"."news__c"',
                'ordering': ['-active_date'],
            },
        ),
    ]
