# Generated by Django 2.0.6 on 2018-06-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.CharField(db_column='sfid', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_image', models.CharField(db_column='thumbnail_image__c', max_length=100)),
                ('main_image', models.CharField(db_column='main_image__c', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description__c', null=True)),
                ('contract_status', models.BooleanField(db_column='contract_status__c', default=False)),
                ('contract_start', models.DateTimeField(blank=True, db_column='contract_start__c', null=True)),
                ('contract_end', models.DateTimeField(blank=True, db_column='contract_end__c', null=True)),
                ('price', models.FloatField(blank=True, db_column='price__c', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date__c')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date__c')),
                ('account', models.ForeignKey(db_column='contact_id__c', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Account')),
            ],
            options={
                'db_table': '"salesforce"."space__c"',
                'ordering': ['-created_date'],
            },
        ),
    ]
